# Generated by Django 2.2.10 on 2022-04-01 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('38aa58e6-2f71-4d54-883c-4f55edd746ff'), primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('check', models.BooleanField()),
                ('title', models.CharField(default='', max_length=256)),
                ('checked_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'todo',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('bf180abb-ccaf-4e1e-8430-8e5361fcaa9f'), primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=256)),
                ('password', models.CharField(default='', max_length=256)),
                ('updated_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
