# Generated by Django 2.2.10 on 2022-04-01 22:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7e6a95b0-1c8f-44db-944c-2dd097420004'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c00cd3fe-bff8-4152-a473-0a0a2eb45649'), primary_key=True, serialize=False),
        ),
    ]
